### ISSUE TITLE
boost::signals2 deadlock with pthread

### ISSUE THREAD

**Issue by AdrianRK** [boostorg/signals2#36]
Hello,

This issue seems to be back on version 1.65 
https://svn.boost.org/trac10/ticket/10721

If the code is compiled with pthread then this will block on the first assert, if it is not build with pthread it will not block,
g++ deadlock-boost-signals2.cpp -pthread -o output
g++ deadlock-boost-signals2.cpp -o output2

[deadlock-boost-signals2.zip](https://github.com/boostorg/signals2/files/3166276/deadlock-boost-signals2.zip)

Thank you,
Adrian Radu

**Comment by fmhess** [comment]
It should be fixed on the develop branch now.  I also added your test to the signals2 test suite.

**Comment by fmhess** [comment]
merged to master
