### ISSUE TITLE
Release numbering and tag stability policy

### ISSUE THREAD

**Issue by nckx** [boostorg/signals2#56]
Hullo!

[Guix](https://guix.gnu.org) provides a boost-signals2 package.  We noticed that the `boost-1.77.0` tag moved significantly between 2019 and 2021.

Looking back, this was (long) before boost 1.77.0 was actually [released](https://lists.boost.org/boost-announce/2021/08/0593.php).  If so, using that tag so early was premature on our part!

Could you confirm my suspicion
- that you develop for _upcoming_ Boost releases using a movable tag,
- but that this tag is not touched once that Boost has been _officially released_ — even to fix bugs found later?

From a brief glance at the repository this seems to be the case, but it would be great if that were a deliberate policy.

Thanks in advance!

**Comment by fmhess** [comment]
I just maintain the boost.signals2 submodule, I don't have anything to do with the release tagging.  Maybe ask Marshall Clow or someone on the Boost Release Team?

**Comment by nckx** [comment]
I'm interested in your policy, not Boost's.  Your [tags](https://github.com/boostorg/signals2/tags) are named `boost-X.Y.Z`.

**Comment by nckx** [comment]
(I don't use Boost myself, so maybe I'm wildly off-base about how any of this works.  It just seems odd that the Boost release team would meddle with your tags?)

**Comment by glenfe** [comment]
The Boost release process creates the tags in each Boost library repository in github.com/boostorg automatically. That said, I don't see how it could have created a 1.77.0 tag before the 1.77.0 release...

**Comment by nckx** [comment]
Oh… OK, interesting way of doing things!

@glenfe: I'm not sure how that would happen either.  Maybe a Guix packager made a mistake.  It's not that important, what really counts is confirmation that tags aren't supposed to move once a release is made :smile: 

Thank you both!

**Comment by nckx** [comment]
> confirmation that tags aren't supposed to move

(If you're confused: no, this is not universally accepted, alas…)
