### ISSUE TITLE
Crashes LLDB on Windows

### ISSUE THREAD

**Issue by everdrone** [boostorg/signals2#66]
When using `clang++` with `c++20` the debugger crashes with the following message
```
error: example.exe :: Class 'std::strong_ordering' has a member 'less' of type 'std::strong_ordering' which does not have a complete definition.
error: example.exe :: Class 'std::partial_ordering' has a member 'less' of type 'std::partial_ordering' which does not have a complete definition.
error: example.exe :: Class 'std::weak_ordering' has a member 'less' of type 'std::weak_ordering' which does not have a complete definition.
Debug adapter exit code=3221225477 (0xc0000005), signal=null.
```

Repository with simple reproductible example: https://github.com/everdrone/clang_signals2

- Clang version:
```
clang version 15.0.7
Target: x86_64-pc-windows-msvc
Thread model: posix
```
- Windows 11, 22621
- Boost 1.81.0
- CMake 3.26.3
- C++20

**Comment by fmhess** [comment]
I don't use windows, so I can't reproduce your problem.  FWIW, I was able to build your example on Linux and debug it with gdb without seeing any problem.

**Comment by fmhess** [comment]
I was also able to debug with lldb without seeing any problem.

**Comment by everdrone** [comment]
I guess I'll wait for other people to try to reproduce as it only happens on windows.

Closing for now
