### ISSUE TITLE
VS 2022 / c++20 signal2 disconnect compilation fail

### ISSUE THREAD

**Issue by laurentcau** [boostorg/signals2#71]
Hi,

We have a compilation issue with VS 2022 / c++20. It compiles fine with c++17.
This code doesn't compile anymore:
```
class CTest
{
public:
	CTest()
	{
		boost::signals2::signal<void()> mySignal;
		mySignal.connect(boost::bind(&CTest::Method, this));
		mySignal.disconnect(boost::bind(&CTest::Method, this));
	}

	void Method()
	{}
};
```
Is there any workaround ?

**Comment by fmhess** [comment]
you could use the develop versions of boost.function and boost.signals2, or disconnect using the connection object returned by the connect call.
